### PR TITLE
Return of the airblast

### PR DESCRIPTION
**Pull request by NicknineTheEagle**
* Added airblast, now it's feature complete, only need to add sounds and particles and solve the problem with players being able to move against airblast direction.
 * ShouldGib() gets called from multiple places so random factor can cause weird issues. Disabled random gibbing until this issue is fixed.

### CODE REVIEW

**Comment by 404UserNotFound** [comment]
> solve the problem with players being able to move against airblast direction.

TF2 solves this by "stunning" the player. Yes, it fires the player_stunned event when you airblast someone. This has been proven by those TF2 stat plugins for SourceMod that give you points for certain things. When stunning is set to give points, airblasting counts as a "stun".

There's probably a TFCond in the game files right now that is used to "stun" the player, thus preventing any movement against the airblast until whenever you become able to move again.

**Comment by NicknineTheEagle** [comment]
And that is one of the main reasons why airblast is hated by some which is why we need to come up with something different

**Comment by Iamgoofball** [comment]
Or we don't, and go for a 100% accurate to live port first, THEN do changes.

**Comment by Deathreus** [comment]
Me randomly chipping in: There's a stun flag in TF2 known as LIMITMOVEMENT which disables forward and backwards movement, this is called in the stun event when airblasted so you can only strafe against the velocity. They remove the stun the moment you touch the ground again. From an include file the flag is given (1 << 2)

**Comment by NicknineTheEagle** [comment]
Hmm, can you explain more on this? Does it just block your forward\back buttons or does it prevent movement in certain directions based on airblast direction?

**Comment by Deathreus** [comment]
As far as I can tell, it seems to just nullify any forward or backwards velocity you try to make pressing forward or back, but you can still navigate while strafing as if you rocket jumped a small distance.

It has nothing to do with direction of blast, it just prevents you from achieving any momentum with the use of those keys.

But at the same time, you can still use backwards button to stop all velocity if you face the opposite direction you were airblasted, this is how I save myself off cliffs many times. Strafe to the side while making a motion to turn 180 degrees then press backwards and it stops momentum. I'm not sure if it's due to a flaw in code that you can do this, but I know you can not pull the same thing off using forward, it won't work.

**Comment by NicknineTheEagle** [comment]
I'm thinking of setting up a system that crops player's speed based on angle between his desired movement direction and direction towards airblast so you can still easily move sideways at any point with airstrafing but not towards airblast origin point.

**Pull request merged**
