### PR TITLE
Wrap TF2C_AUTHDATA_* definitions in quotes for OSX (clang) build

### PR DESCRIPTION
**Pull request by sigsegv-mvm**
Supercedes PR #268.

### CODE REVIEW

**Comment by sigsegv-mvm** [comment]
Actually, don't pull this.

Turns out that clang also interprets the single quotes as meaning that the definition is a string literal.

Will think of something else.

**Comment by sanghakchun** [comment]
Does it have to be a macro? Couldn't we just use the definition directly in the code?

**Comment by PistonMiner** [comment]
It has to be a preprocessor for reasons of compatibility with an internal tool.

**Comment by PistonMiner** [comment]
Resolved in fbfceeb56ff33f70919f878f36a68d6e9b187269

**Pull request closed without merging**
