### PR TITLE
Halp

### PR DESCRIPTION
**Pull request by ckthesorrow**
I Really Need This

### CODE REVIEW

**Comment by PistonMiner** [comment]
Ok, could you just, in a few words, sum up what this PR is even meant to do, because merging a whole bunch of materials doesn't seem like the right idea behind a GitHub repository.

**Comment by Yushe** [comment]
TF2 with working ladders... interesting.

**Comment by danielmm8888** [comment]
func_ladder already does work in TF2C

**Comment by NicknineTheEagle** [comment]
Why would you want to merge a completely different mod into this? TF2C doesn't need HL2 campaign, it's been decided long ago.

**Pull request closed without merging**
