### PR TITLE
Some NPC related fixes to the code

### PR DESCRIPTION
**Pull request by NicknineTheEagle**
Since you don't want to add HL2 NPCs, do NOT merge this completely. Only add NPC-related fixes to TF2 code and base code, like melee weapons making a proper hitsound when hitting NPCs and TF players restricted from using non-TF weapons.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
I think you fucked it up m8s

**Comment by PistonMiner** [comment]
Thats quite a bit changed right there, will take a while to take a look at and resolve

**Comment by NicknineTheEagle** [comment]
Most of the changes are adding files to VPC and changes to HL2 specific code. There's not a whole lot you need to add, actually. But yeah, will take a while to resolve.

**Comment by NicknineTheEagle** [comment]
I'm still not sure if we're going to keep up with the main TF2C branch but if you add NPC related fixes to TF2 code it's gonna be easier for us to keep up. Also, if you ever decide to integrate all of our work into TF2C you will have the base ready.

**Comment by NicknineTheEagle** [comment]
Cancel this, I will later make another pull request only including stuff you need to add.

**Comment by PistonMiner** [comment]
alright

**Pull request closed without merging**
