### PR TITLE
Added support for attributes

### PR DESCRIPTION
**Pull request by NicknineTheEagle**
This is a manual merge of test_schema branch.
Only a couple of attributes are implemented right now.
Also need to fix item_game.txt to use our own weapon models instead of crappy ones from live TF2.

### CODE REVIEW

**Comment by 404UserNotFound** [comment]
I'm not entirely sure what all is taken from item_game.txt but why not modify the code so it only reads from the attribute section, then just include a modified item_game.txt called "attributes.txt" into the TF2C package?

I mean one of the original standards that were set for this mod was ***no*** cosmetics and that's the one thing I'm seeing coming out of this ECON stuff.

**Comment by danielmm8888** [comment]
>I'm not entirely sure what all is taken from item_game.txt but why not modify the code so it only reads from the attribute section, then just include a modified item_game.txt called "attributes.txt" into the TF2C package?

>I mean one of the original standards that were set for this mod was no cosmetics and that's the one thing I'm seeing coming out of this ECON stuff. That, and I was also disappointed to see actual weapons ripped right out of live TF2 for the Medic (as I thought the plan was to be creative and not steal shit from TF2).

Last I've heard, you're working on a custom weapon plugin for tf2 yourself, so you out of all the people out there should know that items_game and the Econ system is so much MUCH more than simply cosmetics and attributes.
This allows us to do a plethora of new and exciting things which simply weren't possible with the old "make a new entity every time we want to make a slight change to a weapon" system. In fact, we don't have to make any new entities at all any more.
Of course, some more complex weapons will still require creating new entities, however this should make things easier for everybody.

We've also addressed this issue previously in the thread.
https://facepunch.com/showthread.php?t=1483571&p=49243951&viewfull=1#post49243951

**Comment by SnowshoeIceboot** [comment]
@404UserNotFound 
https://github.com/SnowshoeIceboot/TF2007

**Comment by 404UserNotFound** [comment]
Yes I'm working alongside Theray and Chdata and some other folks on maintaining MasterOfTheXP's Custom Weapons 2 plugin for TF2, and I run a server for the "cTF2w" group. What I was told by an old friend on the dev team was that the ECON code would allow for a command to equip a weapon or cosmetic item and it would pull the information from the items_game.txt file and pull models from TF2 provided it was installed which is what raised my eyebrow.

And thank you Snowshoe for alerting me that the TF2 2007 project we discussed has finally been forked and ready to go.

**Comment by danielmm8888** [comment]
>But what I was told by an old friend on the dev team was that the ECON code would allow for a command to equip a weapon or cosmetic item and it would pull the information from the items_game.txt file and pull models from TF2 provided it was installed which is what raised my eyebrow.

You can simply say Snowshoe instead of 'old friend'.

**Comment by 404UserNotFound** [comment]
Why can I?

**Comment by PistonMiner** [comment]
>But what I was told by an old friend on the dev team was that the ECON code would allow for a command to equip a weapon or cosmetic item and it would pull the information from the items_game.txt file and pull models from TF2 provided it was installed which is what raised my eyebrow.

Don't make statements about how things work if you don't know how they work. You can make statements about your own code, that's fine, but don't criticise someone else's code because of some non-educated guess.

**Pull request merged**
