### PR TITLE
KOTH CP unlock + conditions system update

### PR DESCRIPTION
**Pull request by NicknineTheEagle**
* Implemented point unlock timer in KOTH
* Multiple dominations\revenges at once no longer trigger ear rape
* Added all condition indexes from live TF2. Most of these are not actually implemented yet. Also added support for all crit conditions from live TF2

### CODE REVIEW

**Comment by NicknineTheEagle** [comment]
Fixed crit effect, it should no longer stay hanging after player is killed.

**Comment by Deathreus** [comment]
If only Valve could fix that problem with crits and heal beams remaining XD

**Comment by NicknineTheEagle** [comment]
Honestly, I don't remember this issue occuring in TF2007 or TF2C.

**Comment by Deathreus** [comment]
Well ,maybe not then, but it does now

**Pull request merged**
